name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: fwilhe2/act-runner-image-inspect@main
    - run: ls -l /opt/hostedtoolcache/
    - name: test
      run: |
          docker pull node
          docker inspect -f "{{ .Size }}"  node:latest | numfmt --to iec --format "%8.4f"
