name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Enable KVM group perms
      run: |
          docker pull node
          BYTES=$(podman inspect -f "{{ .Size }}"  node)
          numfmt --to iec --format "%8.4f" $BYTES
